apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
  namespace: namespace-workflow-1689844876922
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: acrworkflow1689844876922.azurecr.io/image-workflow-1689844876922:latest
          ports:
            - containerPort: 3000