apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: namespace-workflow-1689844876922
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000